# Linear Algebra

In [5]:
import numpy as np

In [7]:
x1 = np.array([[2,1],[1,1] ])
x2 = np.array([[1,1], [1,2]])

In [8]:
np.linalg.solve(x1,x2)

array([[ 0., -1.],
       [ 1.,  3.]])

In [9]:
mat = np.array([[1,3],[2,4]])

In [10]:
mat

array([[1, 3],
       [2, 4]])

In [11]:
np.linalg.det(mat)

-2.0

In [12]:
np.linalg.inv(mat)

array([[-2. ,  1.5],
       [ 1. , -0.5]])

In [13]:
mat.transpose()

array([[1, 2],
       [3, 4]])

In [14]:
np.trace(mat)

5

In [15]:
arr1 = np.array([[1,2],[5,4]])
arr2 = np.array([[2,3],[4,9]])

In [16]:
arr1 * arr2

array([[ 2,  6],
       [20, 36]])

In [17]:
arr1.dot(arr2)

array([[10, 21],
       [26, 51]])

In [18]:
arr1 + arr2

array([[ 3,  5],
       [ 9, 13]])

In [19]:
arr1 - arr2

array([[-1, -1],
       [ 1, -5]])

In [20]:
a = [1,2,1,3,'Apple','Mango',True, False]

In [21]:
a

[1, 2, 1, 3, 'Apple', 'Mango', True, False]

In [22]:
np.array(a)

array(['1', '2', '1', '3', 'Apple', 'Mango', 'True', 'False'],
      dtype='<U11')

In [23]:
a = np.array([1,2,1,1,2,14,45])

In [24]:
a

array([ 1,  2,  1,  1,  2, 14, 45])

In [26]:
b = a

In [27]:
b

array([ 1,  2,  1,  1,  2, 14, 45])

In [28]:
a,b

(array([ 1,  2,  1,  1,  2, 14, 45]), array([ 1,  2,  1,  1,  2, 14, 45]))

In [29]:
a[0]=100

In [31]:
a

array([100,   2,   1,   1,   2,  14,  45])

In [32]:
b

array([100,   2,   1,   1,   2,  14,  45])

In [33]:
id(a)

92149584

In [34]:
id(b)

92149584

In [39]:
x = np.arange(10,50)

In [40]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [43]:
np.append(x,[100,200,300])

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49, 100, 200, 300])

In [51]:
x = np.random.rand(4,3)

In [52]:
x = 10 * x

In [53]:
x

array([[2.63696648, 6.63245162, 8.99854566],
       [1.47356811, 5.00829485, 0.1775212 ],
       [5.76477094, 9.89471955, 3.07596908],
       [7.19796664, 1.31364003, 6.17591715]])

In [57]:
b = np.floor(x)
b

array([[2., 6., 8.],
       [1., 5., 0.],
       [5., 9., 3.],
       [7., 1., 6.]])

In [58]:
np.append(b,[5,6,3])

array([2., 6., 8., 1., 5., 0., 5., 9., 3., 7., 1., 6., 5., 6., 3.])

In [65]:
np.append(b,[[1,2,4]], axis=0)

array([[2., 6., 8.],
       [1., 5., 0.],
       [5., 9., 3.],
       [7., 1., 6.],
       [1., 2., 4.]])

In [66]:
x = np.array([1,2,3,4,5,5,4,3,2,1])

In [67]:
x

array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

In [71]:
np.insert(x,0,-9)

array([-9,  1,  2,  3,  4,  5,  5,  4,  3,  2,  1])

In [70]:
x.size

10

In [76]:
 v = np.arange(36)

In [77]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [111]:
v.reshape(9,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [112]:
np.split(v,6)

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23]),
 array([24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35])]

In [113]:
np.split(v,6)[0]

array([0, 1, 2, 3, 4, 5])

In [114]:
np.split(v,6)[5]

array([30, 31, 32, 33, 34, 35])

In [115]:
np.split(v,6,axis=0)

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23]),
 array([24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35])]

In [118]:
a = np.arange(100,124)

In [119]:
a.size

24

In [120]:
a.reshape(4,6)

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [122]:
a = np.arange(100,124).reshape(4,6)

In [123]:
a

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [130]:
b = np.arange(1,25).reshape(4,6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [135]:
y = np.concatenate((a,b))

In [136]:
y

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123],
       [  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  20,  21,  22,  23,  24]])

In [133]:
np.transpose(y)

array([[100, 106, 112, 118,   1,   7,  13,  19],
       [101, 107, 113, 119,   2,   8,  14,  20],
       [102, 108, 114, 120,   3,   9,  15,  21],
       [103, 109, 115, 121,   4,  10,  16,  22],
       [104, 110, 116, 122,   5,  11,  17,  23],
       [105, 111, 117, 123,   6,  12,  18,  24]])

In [137]:
y.size

48

In [138]:
np.concatenate((a,b))

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123],
       [  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  20,  21,  22,  23,  24]])

In [139]:
np.concatenate((a,b), axis=0)

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123],
       [  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  20,  21,  22,  23,  24]])

In [140]:
np.concatenate((a,b), axis=1)

array([[100, 101, 102, 103, 104, 105,   1,   2,   3,   4,   5,   6],
       [106, 107, 108, 109, 110, 111,   7,   8,   9,  10,  11,  12],
       [112, 113, 114, 115, 116, 117,  13,  14,  15,  16,  17,  18],
       [118, 119, 120, 121, 122, 123,  19,  20,  21,  22,  23,  24]])

In [141]:
v = np.arange(5)

In [142]:
v

array([0, 1, 2, 3, 4])

In [144]:
np.tile(v,5)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4])

In [145]:
u = np.arange(10).reshape(2,5)

In [146]:
u

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [147]:
np.tile(u,2)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [150]:
np.tile(u,(5,3))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [151]:
u

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [152]:
v

array([0, 1, 2, 3, 4])

In [153]:
np.repeat(v,2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [156]:
np.repeat(u,2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [157]:
np.repeat(u,2).reshape(4,5)

array([[0, 0, 1, 1, 2],
       [2, 3, 3, 4, 4],
       [5, 5, 6, 6, 7],
       [7, 8, 8, 9, 9]])

In [161]:
np.repeat(u,2)
np.repeat(u,2, axis=0)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [164]:
np.repeat(u,2, axis=1)

array([[0, 0, 1, 1, 2, 2, 3, 3, 4, 4],
       [5, 5, 6, 6, 7, 7, 8, 8, 9, 9]])