In [2]:
import numpy as np

In [3]:
np.array(list)

array([2, 5, 7, 8])

In [5]:
np.array([list,list])

array([[2, 5, 7, 8],
       [2, 5, 7, 8]])

In [6]:
np.array([[1,2,3],[5,6,7]])

array([[1, 2, 3],
       [5, 6, 7]])

In [7]:
np.array([[3,4,5],[1,2,4],[5,4,3]])

array([[3, 4, 5],
       [1, 2, 4],
       [5, 4, 3]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
5 * np.eye(5)

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.zeros(shape=(4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
5 * np.ones(shape=(4,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(-5,10,3)

array([-5, -2,  1,  4,  7])

In [18]:
np.arange(100,10,-5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

In [20]:
np.linspace(0,20,20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [21]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [22]:
np.random.rand(2,3)

array([[0.53464365, 0.12281095, 0.24530531],
       [0.82585865, 0.32412396, 0.1447085 ]])

In [23]:
np.random.rand(2,3,4)

array([[[0.96526053, 0.85096873, 0.36538441, 0.35738398],
        [0.5300034 , 0.0443441 , 0.38482385, 0.27275252],
        [0.899537  , 0.29023573, 0.79722852, 0.35657306]],

       [[0.82255604, 0.80808923, 0.25235719, 0.75714119],
        [0.9719825 , 0.23351644, 0.52152212, 0.71571508],
        [0.20458581, 0.80760546, 0.89835555, 0.58998225]]])

In [24]:
np.random.randn(4,5)

array([[ 2.4638918 , -0.25196517,  0.30582618,  0.06110608, -1.11010887],
       [-0.98957063, -1.61374787,  0.28500693, -1.48736012,  0.01445736],
       [-0.09666028,  0.16770738,  0.57693698,  0.54937784, -0.13683282],
       [ 0.80837563,  1.23758146,  0.9772279 , -0.52652567,  0.03156617]])

In [31]:
mat = np.random.randn(4,5)
mat.size
mat.shape

(4, 5)

In [25]:
np.random.randint(1,10)

8

In [26]:
np.random.randint(1,10,5)

array([3, 8, 3, 1, 8])

In [27]:
mat = np.random.randint(1,10,5)
type(mat)

numpy.ndarray

In [28]:
mat.size

5

In [29]:
mat.shape

(5,)

In [32]:
arr = np.arange(50,80)

In [33]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [34]:
arr.size

30

In [35]:
arr.shape

(30,)

In [36]:
arr[3:8]

array([53, 54, 55, 56, 57])

In [40]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [41]:
arr[:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [42]:
arr[8:]

array([58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
       75, 76, 77, 78, 79])

In [43]:
arr[:5]

array([50, 51, 52, 53, 54])

In [50]:
sum(arr>50)

29

In [51]:
arr = np.random.rand(3,4)

In [52]:
arr

array([[0.82072733, 0.3475142 , 0.23958745, 0.8411264 ],
       [0.81789039, 0.9254146 , 0.35736608, 0.22733557],
       [0.92914225, 0.41562124, 0.23157471, 0.34344858]])

In [53]:
arr[0,1]

0.3475141982470815

In [54]:
arr[1:]

array([[0.81789039, 0.9254146 , 0.35736608, 0.22733557],
       [0.92914225, 0.41562124, 0.23157471, 0.34344858]])

In [56]:
arr[1,]

array([0.81789039, 0.9254146 , 0.35736608, 0.22733557])

In [63]:
arr[:,3]

array([0.8411264 , 0.22733557, 0.34344858])

In [60]:
arr[1:2]

array([[0.81789039, 0.9254146 , 0.35736608, 0.22733557]])

In [64]:
arr

array([[0.82072733, 0.3475142 , 0.23958745, 0.8411264 ],
       [0.81789039, 0.9254146 , 0.35736608, 0.22733557],
       [0.92914225, 0.41562124, 0.23157471, 0.34344858]])

In [67]:
arr[:,1:2]

array([[0.3475142 ],
       [0.9254146 ],
       [0.41562124]])

In [68]:
arr[:,1]

array([0.3475142 , 0.9254146 , 0.41562124])

In [72]:
arr[:,1:3]

array([[0.3475142 , 0.23958745],
       [0.9254146 , 0.35736608],
       [0.41562124, 0.23157471]])

In [75]:
arr[1:3,1:3]

array([[0.9254146 , 0.35736608],
       [0.41562124, 0.23157471]])

In [76]:
np.sin(arr)

array([[0.73164184, 0.34056166, 0.23730188, 0.74539448],
       [0.72970498, 0.79887022, 0.34980793, 0.22538245],
       [0.80110686, 0.40375836, 0.22951048, 0.33673626]])

In [77]:
np.tan(arr)

array([[1.07327766, 0.36221402, 0.24427949, 1.11816389],
       [1.06719129, 1.32812246, 0.37339873, 0.2313346 ],
       [1.33847666, 0.44133076, 0.23580501, 0.35762173]])

In [78]:
np.cos(arr)

array([[0.68168924, 0.94022219, 0.97143596, 0.66662364],
       [0.68376212, 0.60150343, 0.93682144, 0.97427037],
       [0.59852135, 0.91486567, 0.97330619, 0.94159901]])

In [80]:
np.sum(arr)

6.496748788245841

In [81]:
np.mean(arr)

0.5413957323538201

In [84]:
arr = np.random.rand(3,4)

In [85]:
arr

array([[0.84083079, 0.3777157 , 0.63588173, 0.38864545],
       [0.77784658, 0.15740325, 0.3064211 , 0.04703404],
       [0.14969606, 0.37234406, 0.36199381, 0.19412434]])

In [86]:
arr[0,1]

0.3777156980864259

In [87]:
arr[1,]

array([0.77784658, 0.15740325, 0.3064211 , 0.04703404])

In [90]:
arr[1:,]

array([[0.77784658, 0.15740325, 0.3064211 , 0.04703404],
       [0.14969606, 0.37234406, 0.36199381, 0.19412434]])

# 1,2 row and 1,2 column

In [101]:
arr[:,1:2]

array([[0.3777157 ],
       [0.15740325],
       [0.37234406]])

In [102]:
arr[:,1:3]

array([[0.3777157 , 0.63588173],
       [0.15740325, 0.3064211 ],
       [0.37234406, 0.36199381]])

In [104]:
arr[1:3,1:3]

array([[0.15740325, 0.3064211 ],
       [0.37234406, 0.36199381]])

In [108]:
arr[1:2,:]

array([[0.77784658, 0.15740325, 0.3064211 , 0.04703404]])

In [3]:
a = np.random.rand(3,4)
b = np.random.rand(3,4)

In [4]:
a

array([[0.46462153, 0.44921519, 0.95103477, 0.15897418],
       [0.74143194, 0.26000452, 0.60867989, 0.44954544],
       [0.28667083, 0.91276157, 0.85606947, 0.15064377]])

In [5]:
b

array([[0.99468099, 0.44503564, 0.21635541, 0.88854241],
       [0.43409843, 0.0945304 , 0.77956029, 0.78303532],
       [0.81656727, 0.99927666, 0.70114201, 0.00638001]])

In [7]:
x = np.hstack(a)

In [8]:
x.shape

(12,)

In [12]:
x.size

12

In [13]:
a.shape

(3, 4)

In [14]:
x.shape

(12,)

In [15]:
y  = np.hstack(b)

In [16]:
y

array([0.99468099, 0.44503564, 0.21635541, 0.88854241, 0.43409843,
       0.0945304 , 0.77956029, 0.78303532, 0.81656727, 0.99927666,
       0.70114201, 0.00638001])

In [18]:
z = np.hstack((x,y))

In [19]:
z

array([0.46462153, 0.44921519, 0.95103477, 0.15897418, 0.74143194,
       0.26000452, 0.60867989, 0.44954544, 0.28667083, 0.91276157,
       0.85606947, 0.15064377, 0.99468099, 0.44503564, 0.21635541,
       0.88854241, 0.43409843, 0.0945304 , 0.77956029, 0.78303532,
       0.81656727, 0.99927666, 0.70114201, 0.00638001])

In [20]:
a

array([[0.46462153, 0.44921519, 0.95103477, 0.15897418],
       [0.74143194, 0.26000452, 0.60867989, 0.44954544],
       [0.28667083, 0.91276157, 0.85606947, 0.15064377]])

In [21]:
b

array([[0.99468099, 0.44503564, 0.21635541, 0.88854241],
       [0.43409843, 0.0945304 , 0.77956029, 0.78303532],
       [0.81656727, 0.99927666, 0.70114201, 0.00638001]])

In [22]:
np.hstack((a,b))

array([[0.46462153, 0.44921519, 0.95103477, 0.15897418, 0.99468099,
        0.44503564, 0.21635541, 0.88854241],
       [0.74143194, 0.26000452, 0.60867989, 0.44954544, 0.43409843,
        0.0945304 , 0.77956029, 0.78303532],
       [0.28667083, 0.91276157, 0.85606947, 0.15064377, 0.81656727,
        0.99927666, 0.70114201, 0.00638001]])

In [23]:
np.vstack((a,b))

array([[0.46462153, 0.44921519, 0.95103477, 0.15897418],
       [0.74143194, 0.26000452, 0.60867989, 0.44954544],
       [0.28667083, 0.91276157, 0.85606947, 0.15064377],
       [0.99468099, 0.44503564, 0.21635541, 0.88854241],
       [0.43409843, 0.0945304 , 0.77956029, 0.78303532],
       [0.81656727, 0.99927666, 0.70114201, 0.00638001]])

In [25]:
np.vstack((b,a))

array([[0.99468099, 0.44503564, 0.21635541, 0.88854241],
       [0.43409843, 0.0945304 , 0.77956029, 0.78303532],
       [0.81656727, 0.99927666, 0.70114201, 0.00638001],
       [0.46462153, 0.44921519, 0.95103477, 0.15897418],
       [0.74143194, 0.26000452, 0.60867989, 0.44954544],
       [0.28667083, 0.91276157, 0.85606947, 0.15064377]])

In [26]:
a

array([[0.46462153, 0.44921519, 0.95103477, 0.15897418],
       [0.74143194, 0.26000452, 0.60867989, 0.44954544],
       [0.28667083, 0.91276157, 0.85606947, 0.15064377]])

In [27]:
a = 10 * a

In [28]:
a

array([[4.64621525, 4.49215195, 9.51034773, 1.58974184],
       [7.41431937, 2.60004521, 6.08679894, 4.49545437],
       [2.86670831, 9.12761573, 8.56069466, 1.50643765]])

In [29]:
np.floor(a)

array([[4., 4., 9., 1.],
       [7., 2., 6., 4.],
       [2., 9., 8., 1.]])

In [30]:
np.ceil(a)

array([[ 5.,  5., 10.,  2.],
       [ 8.,  3.,  7.,  5.],
       [ 3., 10.,  9.,  2.]])

In [32]:
new_mat = np.floor(a)

In [34]:
np.sum(new_mat)

57.0

In [37]:
new_mat

array([[4., 4., 9., 1.],
       [7., 2., 6., 4.],
       [2., 9., 8., 1.]])

In [38]:
np.sum(new_mat, axis=0) # Column wise

array([13., 15., 23.,  6.])

In [39]:
np.sum(new_mat, axis=1) # Row Wise 

array([18., 19., 20.])

In [40]:
np.sum(new_mat)

57.0

In [42]:
np.mean(new_mat)
np.mean(new_mat, axis=0)
np.mean(new_mat, axis=1)

array([4.5 , 4.75, 5.  ])

In [43]:
np.mean(new_mat)

4.75

In [44]:
new_mat

array([[4., 4., 9., 1.],
       [7., 2., 6., 4.],
       [2., 9., 8., 1.]])

In [45]:
np.cumsum(new_mat)

array([ 4.,  8., 17., 18., 25., 27., 33., 37., 39., 48., 56., 57.])

In [46]:
np.cumproduct(new_mat)

array([4.000000e+00, 1.600000e+01, 1.440000e+02, 1.440000e+02,
       1.008000e+03, 2.016000e+03, 1.209600e+04, 4.838400e+04,
       9.676800e+04, 8.709120e+05, 6.967296e+06, 6.967296e+06])

In [47]:
np.unique(new_mat)

array([1., 2., 4., 6., 7., 8., 9.])

In [50]:
np.min(new_mat)
np.min(new_mat, axis=0)
np.min(new_mat, axis=1)

array([1., 2., 1.])

In [51]:
np.max(new_mat)
np.max(new_mat, axis=0)
np.max(new_mat, axis=1)

array([9., 7., 9.])

In [55]:
arr = np.arange(20,30)

In [56]:
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [57]:
for value in arr:
    print(value)

20
21
22
23
24
25
26
27
28
29


In [58]:
for index, value in enumerate(arr):
    print(index,value)

0 20
1 21
2 22
3 23
4 24
5 25
6 26
7 27
8 28
9 29
