In [3]:
import numpy as np

In [4]:
arr = np.arange(50,80)

In [5]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [6]:
arr.size

30

In [7]:
arr.shape

(30,)

In [8]:
arr[:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [9]:
arr[4:]

array([54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79])

In [11]:
arr[4:10]

array([54, 55, 56, 57, 58, 59])

In [12]:
arr[1,]

51

In [17]:
arr = np.random.rand(3,4)

In [18]:
arr

array([[0.81418705, 0.45819697, 0.33051211, 0.75109761],
       [0.39102832, 0.65346835, 0.43363762, 0.07211648],
       [0.65542998, 0.35983748, 0.61124081, 0.4200911 ]])

In [20]:
arr[1:,]

array([[0.39102832, 0.65346835, 0.43363762, 0.07211648],
       [0.65542998, 0.35983748, 0.61124081, 0.4200911 ]])

In [22]:
arr

array([[0.81418705, 0.45819697, 0.33051211, 0.75109761],
       [0.39102832, 0.65346835, 0.43363762, 0.07211648],
       [0.65542998, 0.35983748, 0.61124081, 0.4200911 ]])

In [23]:
arr[:,2]

array([0.33051211, 0.43363762, 0.61124081])

In [29]:
arr[1:3,0:2]

array([[0.39102832, 0.65346835],
       [0.65542998, 0.35983748]])