In [1]:
import numpy as np

In [2]:
list = [2,5,7,8]

In [3]:
np.array(list)

array([2, 5, 7, 8])

In [5]:
np.array([list,list])

array([[2, 5, 7, 8],
       [2, 5, 7, 8]])

In [6]:
np.array([[1,2,3],[5,6,7]])

array([[1, 2, 3],
       [5, 6, 7]])

In [7]:
np.array([[3,4,5],[1,2,4],[5,4,3]])

array([[3, 4, 5],
       [1, 2, 4],
       [5, 4, 3]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
5 * np.eye(5)

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.zeros(shape=(4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
5 * np.ones(shape=(4,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(-5,10,3)

array([-5, -2,  1,  4,  7])

In [18]:
np.arange(100,10,-5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

In [20]:
np.linspace(0,20,20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [21]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [22]:
np.random.rand(2,3)

array([[0.53464365, 0.12281095, 0.24530531],
       [0.82585865, 0.32412396, 0.1447085 ]])

In [23]:
np.random.rand(2,3,4)

array([[[0.96526053, 0.85096873, 0.36538441, 0.35738398],
        [0.5300034 , 0.0443441 , 0.38482385, 0.27275252],
        [0.899537  , 0.29023573, 0.79722852, 0.35657306]],

       [[0.82255604, 0.80808923, 0.25235719, 0.75714119],
        [0.9719825 , 0.23351644, 0.52152212, 0.71571508],
        [0.20458581, 0.80760546, 0.89835555, 0.58998225]]])

In [24]:
np.random.randn(4,5)

array([[ 2.4638918 , -0.25196517,  0.30582618,  0.06110608, -1.11010887],
       [-0.98957063, -1.61374787,  0.28500693, -1.48736012,  0.01445736],
       [-0.09666028,  0.16770738,  0.57693698,  0.54937784, -0.13683282],
       [ 0.80837563,  1.23758146,  0.9772279 , -0.52652567,  0.03156617]])

In [25]:
np.random.randint(1,10)

8

In [26]:
np.random.randint(1,10,5)

array([3, 8, 3, 1, 8])

In [27]:
mat = np.random.randint(1,10,5)
type(mat)

numpy.ndarray

In [28]:
mat.size

5

In [29]:
mat.shape

(5,)